In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn.preprocessing import LabelEncoder
from mlxtend.plotting import plot_decision_regions
from sklearn.model_selection import cross_val_score
from sklearn.metrics import plot_roc_curve,roc_curve,roc_auc_score,confusion_matrix,f1_score,classification_report

In [ ]:
df=pd.read_csv('testKNN.txt',sep=',',header=None)
df
df.columns=['Id','RI','Na','Mg','Al','Si','K','Ca','Ba','Fe','TOG']
df

     Id       RI     Na    Mg    Al     Si     K     Ca    Ba    Fe  TOG
0    68  1.52152  13.05  3.65  0.87  72.32  0.19   9.85  0.00  0.17    1
1    69  1.52152  13.12  3.58  0.90  72.20  0.23   9.82  0.00  0.16    1
2    70  1.52300  13.31  3.58  0.82  71.99  0.12  10.17  0.00  0.03    1
3   144  1.51709  13.00  3.47  1.79  72.72  0.66   8.18  0.00  0.00    2
4   145  1.51660  12.99  3.18  1.23  72.97  0.58   8.81  0.00  0.24    2
5   146  1.51839  12.85  3.67  1.24  72.57  0.62   8.68  0.00  0.35    2
6   161  1.51832  13.33  3.34  1.54  72.14  0.56   8.99  0.00  0.00    3
7   162  1.51934  13.64  3.54  0.75  72.65  0.16   8.89  0.15  0.24    3
8   163  1.52211  14.19  3.78  0.91  71.36  0.23   9.14  0.00  0.37    3
9   174  1.52043  13.38  0.00  1.40  72.25  0.33  12.50  0.00  0.00    5
10  175  1.52058  12.85  1.61  2.17  72.18  0.76   9.70  0.24  0.51    5
11  176  1.52119  12.97  0.33  1.51  73.39  0.13  11.27  0.00  0.28    5
12  183  1.51916  14.15  0.00  2.09  72.74  0.00  10.88  0.00  0.00    6
13  184  1.51969  14.56  0.00  0.56  73.48  0.00  11.22  0.00  0.00    6
14  185  1.51115  17.38  0.00  0.34  75.41  0.00   6.65  0.00  0.00    6
15  212  1.52065  14.36  0.00  2.02  73.42  0.00   8.44  1.64  0.00    7
16  213  1.51651  14.38  0.00  1.94  73.61  0.00   8.48  1.57  0.00    7
17  214  1.51711  14.23  0.00  2.08  73.36  0.00   8.62  1.67  0.00    7

In [ ]:
df2=pd.read_csv('trainKNN.txt',sep=',',header=None)
df2
df2.columns=['Id','RI','Na','Mg','Al','Si','K','Ca','Ba','Fe','TOG']
df2

      Id       RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  TOG
0      1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0    1
1      2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0    1
2      3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0    1
3      4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0    1
4      5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0    1
..   ...      ...    ...   ...   ...    ...   ...   ...   ...  ...  ...
191  207  1.51645  14.94  0.00  1.87  73.11  0.00  8.67  1.38  0.0    7
192  208  1.51831  14.39  0.00  1.82  72.86  1.41  6.47  2.88  0.0    7
193  209  1.51640  14.37  0.00  2.74  72.85  0.00  9.45  0.54  0.0    7
194  210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0    7
195  211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0    7

[196 rows x 11 columns]

In [ ]:
df.isnull().sum()

Id     0
RI     0
Na     0
Mg     0
Al     0
Si     0
K      0
Ca     0
Ba     0
Fe     0
TOG    0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      18 non-null     int64
 1   RI      18 non-null     float64
 2   Na      18 non-null     float64
 3   Mg      18 non-null     float64
 4   Al      18 non-null     float64
 5   Si      18 non-null     float64
 6   K       18 non-null     float64
 7   Ca      18 non-null     float64
 8   Ba      18 non-null     float64
 9   Fe      18 non-null     float64
 10  TOG     18 non-null     int64
dtypes: float64(9), int64(2)
memory usage: 1.7 KB

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      18 non-null     int64
 1   RI      18 non-null     float64
 2   Na      18 non-null     float64
 3   Mg      18 non-null     float64
 4   Al      18 non-null     float64
 5   Si      18 non-null     float64
 6   K       18 non-null     float64
 7   Ca      18 non-null     float64
 8   Ba      18 non-null     float64
 9   Fe      18 non-null     float64
 10  TOG     18 non-null     int64
dtypes: float64(9), int64(2)
memory usage: 1.7 KB

In [ ]:
df2.isnull().sum()

Id     0
RI     0
Na     0
Mg     0
Al     0
Si     0
K      0
Ca     0
Ba     0
Fe     0
TOG    0
dtype: int64

In [ ]:
#df=df.drop(columns='Id')
#df2=df2.drop(columns='Id')

In [ ]:
df

     Id       RI     Na    Mg    Al     Si     K     Ca    Ba    Fe  TOG
0    68  1.52152  13.05  3.65  0.87  72.32  0.19   9.85  0.00  0.17    1
1    69  1.52152  13.12  3.58  0.90  72.20  0.23   9.82  0.00  0.16    1
2    70  1.52300  13.31  3.58  0.82  71.99  0.12  10.17  0.00  0.03    1
3   144  1.51709  13.00  3.47  1.79  72.72  0.66   8.18  0.00  0.00    2
4   145  1.51660  12.99  3.18  1.23  72.97  0.58   8.81  0.00  0.24    2
5   146  1.51839  12.85  3.67  1.24  72.57  0.62   8.68  0.00  0.35    2
6   161  1.51832  13.33  3.34  1.54  72.14  0.56   8.99  0.00  0.00    3
7   162  1.51934  13.64  3.54  0.75  72.65  0.16   8.89  0.15  0.24    3
8   163  1.52211  14.19  3.78  0.91  71.36  0.23   9.14  0.00  0.37    3
9   174  1.52043  13.38  0.00  1.40  72.25  0.33  12.50  0.00  0.00    5
10  175  1.52058  12.85  1.61  2.17  72.18  0.76   9.70  0.24  0.51    5
11  176  1.52119  12.97  0.33  1.51  73.39  0.13  11.27  0.00  0.28    5
12  183  1.51916  14.15  0.00  2.09  72.74  0.00  10.88  0.00  0.00    6
13  184  1.51969  14.56  0.00  0.56  73.48  0.00  11.22  0.00  0.00    6
14  185  1.51115  17.38  0.00  0.34  75.41  0.00   6.65  0.00  0.00    6
15  212  1.52065  14.36  0.00  2.02  73.42  0.00   8.44  1.64  0.00    7
16  213  1.51651  14.38  0.00  1.94  73.61  0.00   8.48  1.57  0.00    7
17  214  1.51711  14.23  0.00  2.08  73.36  0.00   8.62  1.67  0.00    7

##Spliting the data into train and split

In [ ]:
X_train=df.iloc[:,:-1]
y_train=df.iloc[:,-1]
X_test=df.iloc[:,:-1]
y_test=df.iloc[:,-1]

##Scaling the data

In [ ]:
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

##Fitiing the KNN

In [ ]:
for k in range(1,10):
  X=X_train,y_train
  knn=KNeighborsClassifier(k)
  knn.fit(X_train,y_train)
  print("K : ", k, " Train Accuracy : ", knn.score(X_train,y_train), " cross Value Accuracy : ", np.mean(cross_val_score(knn,X_train,y_train, cv=2)))

K :  1  Train Accuracy :  1.0  cross Value Accuracy :  0.7222222222222222
K :  2  Train Accuracy :  0.7777777777777778  cross Value Accuracy :  0.38888888888888884
K :  3  Train Accuracy :  0.8333333333333334  cross Value Accuracy :  0.2777777777777778
K :  4  Train Accuracy :  0.7222222222222222  cross Value Accuracy :  0.2222222222222222
K :  5  Train Accuracy :  0.6666666666666666  cross Value Accuracy :  0.2222222222222222
K :  6  Train Accuracy :  0.6111111111111112  cross Value Accuracy :  0.1111111111111111
K :  7  Train Accuracy :  0.6111111111111112  cross Value Accuracy :  0.1111111111111111
K :  8  Train Accuracy :  0.6111111111111112  cross Value Accuracy :  0.1111111111111111
K :  9  Train Accuracy :  0.6111111111111112  cross Value Accuracy :  0.1111111111111111

In [ ]:
for k in range(2,4):
  X=X_train,y_train
  knn=KNeighborsClassifier(1)
  knn.fit(X_train,y_train)
  print("K : ", 1, " Train Accuracy : ", knn.score(X_train,y_train), " cross Value Accuracy : ",k," is ", np.mean(cross_val_score(knn,X_train,y_train, cv=k)))

K :  1  Train Accuracy :  1.0  cross Value Accuracy :  2  is  0.7222222222222222
K :  1  Train Accuracy :  1.0  cross Value Accuracy :  3  is  0.7222222222222222

In [ ]:
X=X_train,y_train
knn=KNeighborsClassifier(1)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [ ]:
y_pred=knn.predict(X_test)

In [ ]:
pd.DataFrame({'actual':y_test,'predict':y_pred}).head(10)

   actual  predict
0       1        1
1       1        1
2       1        1
3       2        2
4       2        2
5       2        2
6       3        3
7       3        3
8       3        3
9       5        5

In [ ]:
knn.score(X_test,y_test)

1.0

In [23]:
roc_auc_score(y_test,knn.predict_proba(X_test)[:,:],multi_class="ovo")

1.0

In [ ]:
conf_matrix = confusion_matrix(y_test,y_pred)
print(conf_matrix )